import json

VR_PARAM_MAP_JSON_STR = """
{
   "1band_sr16000_hl512":{
      "bins":1024,
      "unstable_bins":0,
      "reduction_bins":0,
      "band":{
         "1":{
            "sr":16000,
            "hl":512,
            "n_fft":2048,
            "crop_start":0,
            "crop_stop":1024,
            "hpf_start":-1,
            "res_type":"sinc_best"
         }
      },
      "sr":16000,
      "pre_filter_start":1023,
      "pre_filter_stop":1024
   },
   "1band_sr32000_hl512":{
      "bins":1024,
      "unstable_bins":0,
      "reduction_bins":0,
      "band":{
         "1":{
            "sr":32000,
            "hl":512,
            "n_fft":2048,
            "crop_start":0,
            "crop_stop":1024,
            "hpf_start":-1,
            "res_type":"kaiser_fast"
         }
      },
      "sr":32000,
      "pre_filter_start":1000,
      "pre_filter_stop":1021
   },
   "1band_sr33075_hl384":{
      "bins":1024,
      "unstable_bins":0,
      "reduction_bins":0,
      "band":{
         "1":{
            "sr":33075,
            "hl":384,
            "n_fft":2048,
            "crop_start":0,
            "crop_stop":1024,
            "hpf_start":-1,
            "res_type":"sinc_best"
         }
      },
      "sr":33075,
      "pre_filter_start":1000,
      "pre_filter_stop":1021
   },
   "1band_sr44100_hl1024":{
      "bins":1024,
      "unstable_bins":0,
      "reduction_bins":0,
      "band":{
         "1":{
            "sr":44100,
            "hl":1024,
            "n_fft":2048,
            "crop_start":0,
            "crop_stop":1024,
            "hpf_start":-1,
            "res_type":"sinc_best"
         }
      },
      "sr":44100,
      "pre_filter_start":1023,
      "pre_filter_stop":1024
   },
   "1band_sr44100_hl256":{
      "bins":256,
      "unstable_bins":0,
      "reduction_bins":0,
      "band":{
         "1":{
            "sr":44100,
            "hl":256,
            "n_fft":512,
            "crop_start":0,
            "crop_stop":256,
            "hpf_start":-1,
            "res_type":"sinc_best"
         }
      },
      "sr":44100,
      "pre_filter_start":256,
      "pre_filter_stop":256
   },
   "1band_sr44100_hl512":{
      "bins":1024,
      "unstable_bins":0,
      "reduction_bins":0,
      "band":{
         "1":{
            "sr":44100,
            "hl":512,
            "n_fft":2048,
            "crop_start":0,
            "crop_stop":1024,
            "hpf_start":-1,
            "res_type":"sinc_best"
         }
      },
      "sr":44100,
      "pre_filter_start":1023,
      "pre_filter_stop":1024
   },
   "1band_sr44100_hl512_cut":{
      "bins":1024,
      "unstable_bins":0,
      "reduction_bins":0,
      "band":{
         "1":{
            "sr":44100,
            "hl":512,
            "n_fft":2048,
            "crop_start":0,
            "crop_stop":700,
            "hpf_start":-1,
            "res_type":"sinc_best"
         }
      },
      "sr":44100,
      "pre_filter_start":1023,
      "pre_filter_stop":700
   },
   "1band_sr44100_hl512_nf1024":{
      "bins":512,
      "unstable_bins":0,
      "reduction_bins":0,
      "band":{
         "1":{
            "sr":44100,
            "hl":512,
            "n_fft":1024,
            "crop_start":0,
            "crop_stop":512,
            "hpf_start":-1,
            "res_type":"sinc_best"
         }
      },
      "sr":44100,
      "pre_filter_start":511,
      "pre_filter_stop":512
   },
   "2band_32000":{
      "bins":768,
      "unstable_bins":7,
      "reduction_bins":705,
      "band":{
         "1":{
            "sr":6000,
            "hl":66,
            "n_fft":512,
            "crop_start":0,
            "crop_stop":240,
            "lpf_start":60,
            "lpf_stop":118,
            "res_type":"sinc_fastest"
         },
         "2":{
            "sr":32000,
            "hl":352,
            "n_fft":1024,
            "crop_start":22,
            "crop_stop":505,
            "hpf_start":44,
            "hpf_stop":23,
            "res_type":"sinc_medium"
         }
      },
      "sr":32000,
      "pre_filter_start":710,
      "pre_filter_stop":731
   },
   "2band_44100_lofi":{
      "bins":512,
      "unstable_bins":7,
      "reduction_bins":510,
      "band":{
         "1":{
            "sr":11025,
            "hl":160,
            "n_fft":768,
            "crop_start":0,
            "crop_stop":192,
            "lpf_start":41,
            "lpf_stop":139,
            "res_type":"sinc_fastest"
         },
         "2":{
            "sr":44100,
            "hl":640,
            "n_fft":1024,
            "crop_start":10,
            "crop_stop":320,
            "hpf_start":47,
            "hpf_stop":15,
            "res_type":"sinc_medium"
         }
      },
      "sr":44100,
      "pre_filter_start":510,
      "pre_filter_stop":512
   },
   "2band_48000":{
      "bins":768,
      "unstable_bins":7,
      "reduction_bins":705,
      "band":{
         "1":{
            "sr":6000,
            "hl":66,
            "n_fft":512,
            "crop_start":0,
            "crop_stop":240,
            "lpf_start":60,
            "lpf_stop":240,
            "res_type":"sinc_fastest"
         },
         "2":{
            "sr":48000,
            "hl":528,
            "n_fft":1536,
            "crop_start":22,
            "crop_stop":505,
            "hpf_start":82,
            "hpf_stop":22,
            "res_type":"sinc_medium"
         }
      },
      "sr":48000,
      "pre_filter_start":710,
      "pre_filter_stop":731
   },
   "3band_44100":{
      "bins":768,
      "unstable_bins":5,
      "reduction_bins":733,
      "band":{
         "1":{
            "sr":11025,
            "hl":128,
            "n_fft":768,
            "crop_start":0,
            "crop_stop":278,
            "lpf_start":28,
            "lpf_stop":140,
            "res_type":"polyphase"
         },
         "2":{
            "sr":22050,
            "hl":256,
            "n_fft":768,
            "crop_start":14,
            "crop_stop":322,
            "hpf_start":70,
            "hpf_stop":14,
            "lpf_start":283,
            "lpf_stop":314,
            "res_type":"polyphase"
         },
         "3":{
            "sr":44100,
            "hl":512,
            "n_fft":768,
            "crop_start":131,
            "crop_stop":313,
            "hpf_start":154,
            "hpf_stop":141,
            "res_type":"sinc_medium"
         }
      },
      "sr":44100,
      "pre_filter_start":757,
      "pre_filter_stop":768
   },
   "3band_44100_mid":{
      "mid_side":true,
      "bins":768,
      "unstable_bins":5,
      "reduction_bins":733,
      "band":{
         "1":{
            "sr":11025,
            "hl":128,
            "n_fft":768,
            "crop_start":0,
            "crop_stop":278,
            "lpf_start":28,
            "lpf_stop":140,
            "res_type":"polyphase"
         },
         "2":{
            "sr":22050,
            "hl":256,
            "n_fft":768,
            "crop_start":14,
            "crop_stop":322,
            "hpf_start":70,
            "hpf_stop":14,
            "lpf_start":283,
            "lpf_stop":314,
            "res_type":"polyphase"
         },
         "3":{
            "sr":44100,
            "hl":512,
            "n_fft":768,
            "crop_start":131,
            "crop_stop":313,
            "hpf_start":154,
            "hpf_stop":141,
            "res_type":"sinc_medium"
         }
      },
      "sr":44100,
      "pre_filter_start":757,
      "pre_filter_stop":768
   },
   "3band_44100_msb2":{
      "mid_side_b2":true,
      "bins":640,
      "unstable_bins":7,
      "reduction_bins":565,
      "band":{
         "1":{
            "sr":11025,
            "hl":108,
            "n_fft":1024,
            "crop_start":0,
            "crop_stop":187,
            "lpf_start":92,
            "lpf_stop":186,
            "res_type":"polyphase"
         },
         "2":{
            "sr":22050,
            "hl":216,
            "n_fft":768,
            "crop_start":0,
            "crop_stop":212,
            "hpf_start":68,
            "hpf_stop":34,
            "lpf_start":174,
            "lpf_stop":209,
            "res_type":"polyphase"
         },
         "3":{
            "sr":44100,
            "hl":432,
            "n_fft":640,
            "crop_start":66,
            "crop_stop":307,
            "hpf_start":86,
            "hpf_stop":72,
            "res_type":"kaiser_fast"
         }
      },
      "sr":44100,
      "pre_filter_start":639,
      "pre_filter_stop":640
   },
   "4band_44100":{
      "bins":768,
      "unstable_bins":7,
      "reduction_bins":668,
      "band":{
         "1":{
            "sr":11025,
            "hl":128,
            "n_fft":1024,
            "crop_start":0,
            "crop_stop":186,
            "lpf_start":37,
            "lpf_stop":73,
            "res_type":"polyphase"
         },
         "2":{
            "sr":11025,
            "hl":128,
            "n_fft":512,
            "crop_start":4,
            "crop_stop":185,
            "hpf_start":36,
            "hpf_stop":18,
            "lpf_start":93,
            "lpf_stop":185,
            "res_type":"polyphase"
         },
         "3":{
            "sr":22050,
            "hl":256,
            "n_fft":512,
            "crop_start":46,
            "crop_stop":186,
            "hpf_start":93,
            "hpf_stop":46,
            "lpf_start":164,
            "lpf_stop":186,
            "res_type":"polyphase"
         },
         "4":{
            "sr":44100,
            "hl":512,
            "n_fft":768,
            "crop_start":121,
            "crop_stop":382,
            "hpf_start":138,
            "hpf_stop":123,
            "res_type":"sinc_medium"
         }
      },
      "sr":44100,
      "pre_filter_start":740,
      "pre_filter_stop":768
   },
   "4band_44100_mid":{
      "bins":768,
      "unstable_bins":7,
      "mid_side":true,
      "reduction_bins":668,
      "band":{
         "1":{
            "sr":11025,
            "hl":128,
            "n_fft":1024,
            "crop_start":0,
            "crop_stop":186,
            "lpf_start":37,
            "lpf_stop":73,
            "res_type":"polyphase"
         },
         "2":{
            "sr":11025,
            "hl":128,
            "n_fft":512,
            "crop_start":4,
            "crop_stop":185,
            "hpf_start":36,
            "hpf_stop":18,
            "lpf_start":93,
            "lpf_stop":185,
            "res_type":"polyphase"
         },
         "3":{
            "sr":22050,
            "hl":256,
            "n_fft":512,
            "crop_start":46,
            "crop_stop":186,
            "hpf_start":93,
            "hpf_stop":46,
            "lpf_start":164,
            "lpf_stop":186,
            "res_type":"polyphase"
         },
         "4":{
            "sr":44100,
            "hl":512,
            "n_fft":768,
            "crop_start":121,
            "crop_stop":382,
            "hpf_start":138,
            "hpf_stop":123,
            "res_type":"sinc_medium"
         }
      },
      "sr":44100,
      "pre_filter_start":740,
      "pre_filter_stop":768
   },
   "4band_44100_msb":{
      "mid_side_b":true,
      "bins":768,
      "unstable_bins":7,
      "reduction_bins":668,
      "band":{
         "1":{
            "sr":11025,
            "hl":128,
            "n_fft":1024,
            "crop_start":0,
            "crop_stop":186,
            "lpf_start":37,
            "lpf_stop":73,
            "res_type":"polyphase"
         },
         "2":{
            "sr":11025,
            "hl":128,
            "n_fft":512,
            "crop_start":4,
            "crop_stop":185,
            "hpf_start":36,
            "hpf_stop":18,
            "lpf_start":93,
            "lpf_stop":185,
            "res_type":"polyphase"
         },
         "3":{
            "sr":22050,
            "hl":256,
            "n_fft":512,
            "crop_start":46,
            "crop_stop":186,
            "hpf_start":93,
            "hpf_stop":46,
            "lpf_start":164,
            "lpf_stop":186,
            "res_type":"polyphase"
         },
         "4":{
            "sr":44100,
            "hl":512,
            "n_fft":768,
            "crop_start":121,
            "crop_stop":382,
            "hpf_start":138,
            "hpf_stop":123,
            "res_type":"sinc_medium"
         }
      },
      "sr":44100,
      "pre_filter_start":740,
      "pre_filter_stop":768
   },
   "4band_44100_msb2":{
      "mid_side_b":true,
      "bins":768,
      "unstable_bins":7,
      "reduction_bins":668,
      "band":{
         "1":{
            "sr":11025,
            "hl":128,
            "n_fft":1024,
            "crop_start":0,
            "crop_stop":186,
            "lpf_start":37,
            "lpf_stop":73,
            "res_type":"polyphase"
         },
         "2":{
            "sr":11025,
            "hl":128,
            "n_fft":512,
            "crop_start":4,
            "crop_stop":185,
            "hpf_start":36,
            "hpf_stop":18,
            "lpf_start":93,
            "lpf_stop":185,
            "res_type":"polyphase"
         },
         "3":{
            "sr":22050,
            "hl":256,
            "n_fft":512,
            "crop_start":46,
            "crop_stop":186,
            "hpf_start":93,
            "hpf_stop":46,
            "lpf_start":164,
            "lpf_stop":186,
            "res_type":"polyphase"
         },
         "4":{
            "sr":44100,
            "hl":512,
            "n_fft":768,
            "crop_start":121,
            "crop_stop":382,
            "hpf_start":138,
            "hpf_stop":123,
            "res_type":"sinc_medium"
         }
      },
      "sr":44100,
      "pre_filter_start":740,
      "pre_filter_stop":768
   },
   "4band_44100_reverse":{
      "reverse":true,
      "bins":768,
      "unstable_bins":7,
      "reduction_bins":668,
      "band":{
         "1":{
            "sr":11025,
            "hl":128,
            "n_fft":1024,
            "crop_start":0,
            "crop_stop":186,
            "lpf_start":37,
            "lpf_stop":73,
            "res_type":"polyphase"
         },
         "2":{
            "sr":11025,
            "hl":128,
            "n_fft":512,
            "crop_start":4,
            "crop_stop":185,
            "hpf_start":36,
            "hpf_stop":18,
            "lpf_start":93,
            "lpf_stop":185,
            "res_type":"polyphase"
         },
         "3":{
            "sr":22050,
            "hl":256,
            "n_fft":512,
            "crop_start":46,
            "crop_stop":186,
            "hpf_start":93,
            "hpf_stop":46,
            "lpf_start":164,
            "lpf_stop":186,
            "res_type":"polyphase"
         },
         "4":{
            "sr":44100,
            "hl":512,
            "n_fft":768,
            "crop_start":121,
            "crop_stop":382,
            "hpf_start":138,
            "hpf_stop":123,
            "res_type":"sinc_medium"
         }
      },
      "sr":44100,
      "pre_filter_start":740,
      "pre_filter_stop":768
   },
   "4band_44100_sw":{
      "stereo_w":true,
      "bins":768,
      "unstable_bins":7,
      "reduction_bins":668,
      "band":{
         "1":{
            "sr":11025,
            "hl":128,
            "n_fft":1024,
            "crop_start":0,
            "crop_stop":186,
            "lpf_start":37,
            "lpf_stop":73,
            "res_type":"polyphase"
         },
         "2":{
            "sr":11025,
            "hl":128,
            "n_fft":512,
            "crop_start":4,
            "crop_stop":185,
            "hpf_start":36,
            "hpf_stop":18,
            "lpf_start":93,
            "lpf_stop":185,
            "res_type":"polyphase"
         },
         "3":{
            "sr":22050,
            "hl":256,
            "n_fft":512,
            "crop_start":46,
            "crop_stop":186,
            "hpf_start":93,
            "hpf_stop":46,
            "lpf_start":164,
            "lpf_stop":186,
            "res_type":"polyphase"
         },
         "4":{
            "sr":44100,
            "hl":512,
            "n_fft":768,
            "crop_start":121,
            "crop_stop":382,
            "hpf_start":138,
            "hpf_stop":123,
            "res_type":"sinc_medium"
         }
      },
      "sr":44100,
      "pre_filter_start":740,
      "pre_filter_stop":768
   },
   "4band_v2":{
      "bins":672,
      "unstable_bins":8,
      "reduction_bins":637,
      "band":{
         "1":{
            "sr":7350,
            "hl":80,
            "n_fft":640,
            "crop_start":0,
            "crop_stop":85,
            "lpf_start":25,
            "lpf_stop":53,
            "res_type":"polyphase"
         },
         "2":{
            "sr":7350,
            "hl":80,
            "n_fft":320,
            "crop_start":4,
            "crop_stop":87,
            "hpf_start":25,
            "hpf_stop":12,
            "lpf_start":31,
            "lpf_stop":62,
            "res_type":"polyphase"
         },
         "3":{
            "sr":14700,
            "hl":160,
            "n_fft":512,
            "crop_start":17,
            "crop_stop":216,
            "hpf_start":48,
            "hpf_stop":24,
            "lpf_start":139,
            "lpf_stop":210,
            "res_type":"polyphase"
         },
         "4":{
            "sr":44100,
            "hl":480,
            "n_fft":960,
            "crop_start":78,
            "crop_stop":383,
            "hpf_start":130,
            "hpf_stop":86,
            "res_type":"kaiser_fast"
         }
      },
      "sr":44100,
      "pre_filter_start":668,
      "pre_filter_stop":672
   },
   "4band_v2_sn":{
      "bins":672,
      "unstable_bins":8,
      "reduction_bins":637,
      "band":{
         "1":{
            "sr":7350,
            "hl":80,
            "n_fft":640,
            "crop_start":0,
            "crop_stop":85,
            "lpf_start":25,
            "lpf_stop":53,
            "res_type":"polyphase"
         },
         "2":{
            "sr":7350,
            "hl":80,
            "n_fft":320,
            "crop_start":4,
            "crop_stop":87,
            "hpf_start":25,
            "hpf_stop":12,
            "lpf_start":31,
            "lpf_stop":62,
            "res_type":"polyphase"
         },
         "3":{
            "sr":14700,
            "hl":160,
            "n_fft":512,
            "crop_start":17,
            "crop_stop":216,
            "hpf_start":48,
            "hpf_stop":24,
            "lpf_start":139,
            "lpf_stop":210,
            "res_type":"polyphase"
         },
         "4":{
            "sr":44100,
            "hl":480,
            "n_fft":960,
            "crop_start":78,
            "crop_stop":383,
            "hpf_start":130,
            "hpf_stop":86,
            "convert_channels":"stereo_n",
            "res_type":"kaiser_fast"
         }
      },
      "sr":44100,
      "pre_filter_start":668,
      "pre_filter_stop":672
   },
   "4band_v3":{
      "bins":672,
      "unstable_bins":8,
      "reduction_bins":530,
      "band":{
         "1":{
            "sr":7350,
            "hl":80,
            "n_fft":640,
            "crop_start":0,
            "crop_stop":85,
            "lpf_start":25,
            "lpf_stop":53,
            "res_type":"polyphase"
         },
         "2":{
            "sr":7350,
            "hl":80,
            "n_fft":320,
            "crop_start":4,
            "crop_stop":87,
            "hpf_start":25,
            "hpf_stop":12,
            "lpf_start":31,
            "lpf_stop":62,
            "res_type":"polyphase"
         },
         "3":{
            "sr":14700,
            "hl":160,
            "n_fft":512,
            "crop_start":17,
            "crop_stop":216,
            "hpf_start":48,
            "hpf_stop":24,
            "lpf_start":139,
            "lpf_stop":210,
            "res_type":"polyphase"
         },
         "4":{
            "sr":44100,
            "hl":480,
            "n_fft":960,
            "crop_start":78,
            "crop_stop":383,
            "hpf_start":130,
            "hpf_stop":86,
            "res_type":"kaiser_fast"
         }
      },
      "sr":44100,
      "pre_filter_start":668,
      "pre_filter_stop":672
   },
   "ensemble":{
      "mid_side_b2":true,
      "bins":1280,
      "unstable_bins":7,
      "reduction_bins":565,
      "band":{
         "1":{
            "sr":11025,
            "hl":108,
            "n_fft":2048,
            "crop_start":0,
            "crop_stop":374,
            "lpf_start":92,
            "lpf_stop":186,
            "res_type":"polyphase"
         },
         "2":{
            "sr":22050,
            "hl":216,
            "n_fft":1536,
            "crop_start":0,
            "crop_stop":424,
            "hpf_start":68,
            "hpf_stop":34,
            "lpf_start":348,
            "lpf_stop":418,
            "res_type":"polyphase"
         },
         "3":{
            "sr":44100,
            "hl":432,
            "n_fft":1280,
            "crop_start":132,
            "crop_stop":614,
            "hpf_start":172,
            "hpf_stop":144,
            "res_type":"polyphase"
         }
      },
      "sr":44100,
      "pre_filter_start":1280,
      "pre_filter_stop":1280
   }
}
"""


def int_keys(d):
    r = {}
    for k, v in d:
        if k.isdigit():
            k = int(k)
        r[k] = v
    return r


VR_PARAM_MAP = json.loads(VR_PARAM_MAP_JSON_STR, object_pairs_hook=int_keys)
