name: Dev UI Build
on:
  push:
    paths:
      - .github/**
      - electron/**
      - ui/**
      - server/**
      - python/**
      - api/**
      - shared/**
      - package.json
    branches-ignore:
      - release
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_ENV: production
  APP_ENV: production
  APPLE_ID: ${{ secrets.APPLE_ID }}
  APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
  APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
  CSC_LINK: ${{ secrets.CSC_LINK }}
  CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      python: ${{ steps.changes.outputs.python }}
      ui: ${{ steps.changes.outputs.ui }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ github.ref }}
          filters: |
            python:
              - 'python/**'
            ui:
              - '.github/**'
              - 'electron/**'
              - 'ui/**'
              - 'server/**'
              - 'python/**'
              - 'api/**'
              - 'shared/**'
              - 'package.json'
  build-ui:
    needs: [paths-filter]
    if: needs.paths-filter.outputs.ui == 'true'
    strategy:
      matrix:
        include:
          - platform: mac
            runner: ghcr.io/cirruslabs/macos-monterey-xcode:latest
            arch: arm64
            npm_config_platform: darwin
    uses: ./.github/workflows/build-ui.yml
    with:
      runner: ${{ matrix.runner }}
      arch: ${{ matrix.arch }}
      npm_config_platform: ${{ matrix.npm_config_platform }}
      platform: ${{ matrix.platform }}
      dev: true
    secrets: inherit
  build-server:
    needs: [paths-filter]
    if: needs.paths-filter.outputs.python == 'true'
    strategy:
      matrix:
        include:
          - platform: mac
            runner: ghcr.io/cirruslabs/macos-monterey-xcode:latest
            arch: arm64
            npm_config_platform: darwin
    uses: ./.github/workflows/build-server.yml
    with:
      runner: ${{ matrix.runner }}
      arch: ${{ matrix.arch }}
      npm_config_platform: ${{ matrix.npm_config_platform }}
      platform: ${{ matrix.platform }}
      dev: true
    secrets: inherit
